# 响应页面默认后缀
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
#单实例路由
zuul:
  routes:
    api-node1:
      path: /ribbon/** #指定路径
      serviceId: spring-cloud-ribbon-consumer #指定服务
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization
    api-node2:
      path: /feign/**
      url: http://localhost:8766
    api-node3:
      path: /wap/**
      url: forward:/wap
